// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: '',
    appId: '1:197100130024:web:a49c6f4edc8e8b80bc035d',
    messagingSenderId: '197100130024',
    projectId: 'speakup-final',
    authDomain: 'speakup-final.firebaseapp.com',
    storageBucket: 'speakup-final.firebasestorage.app',
    measurementId: 'G-S9VRBQS19W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: '',
    appId: '1:197100130024:android:6c1507007f473301bc035d',
    messagingSenderId: '197100130024',
    projectId: 'speakup-final',
    storageBucket: 'speakup-final.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: '',
    appId: '1:197100130024:ios:62eac7e29bf78df6bc035d',
    messagingSenderId: '197100130024',
    projectId: 'speakup-final',
    storageBucket: 'speakup-final.firebasestorage.app',
    iosClientId: '197100130024-aa15tasf613o8r1u82sc91vjo8101ioi.apps.googleusercontent.com',
    iosBundleId: 'com.example.speakupFinal',
  );
}
